global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'resumatch'
    static_configs:
      - targets: ['resumatch:8000']

  - job_name: 'system'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'static'
    static_configs:
      - targets: [ 'static:8096' ]

  - job_name: 'auth'
    static_configs:
      - targets: [ 'auth:8095' ]