http:
  host: "0.0.0.0"
  port: "8000"
  readTimeout: "10s"
  writeTimeout: "10s"
  maxHeaderBytes: 1048576
  corsAllowedOrigins:
    - "https://resumatch.tech"

microservices:
  auth_service:
    host: "auth"
    port: "8081"
  static_service:
    host: "static"
    port: "8083"

session:
  cookieName: "session_id"
  lifetime: "24h"
  httpOnly: true
  secure: false
  sameSite: "Strict"

csrf:
  cookieName: "csrf_token"
  lifetime: "1h"
  httpOnly: true
  secure: false
  sameSite: "Strict"

postgres:
  host: "localhost"
  port: "5432"
  user: "postgres"
  dbname: "mydb"
  sslmode: "disable"

resume:
  staticPath: "static/templates"
  staticFile: "resume_pdf.html"
  paperWidth:  "12"
  paperHeight: "18"
  generateURL: "http://gotenberg:3000/forms/chromium/convert/html"

