http:
  host: "0.0.0.0"
  port: "8000"
  readTimeout: "10s"
  writeTimeout: "10s"
  maxHeaderBytes: 1048576
  corsAllowedOrigins:
    - "http://localhost:8001"

microservices:
  auth_service:
    host: "auth"
    port: "8081"

session:
  cookieName: "session_id"
  lifetime: "24h"
  httpOnly: true
  secure: false
  sameSite: "Strict"

csrf:
  cookieName: "csrf_token"
  lifetime: "1h"
  httpOnly: true
  secure: false
  sameSite: "Strict"

postgres:
  host: "localhost"
  port: "5432"
  user: "postgres"
  dbname: "mydb"
  sslmode: "disable"

minio:
  config:
    internal_endpoint: "minio:9000"
    public_endpoint: "localhost:9000"
    root_user: "minioadmin"
    root_password: "miniopassword"
    use_ssl: false
    scheme: "http"
  buckets:
    applicant_bucket: "applicant"
    employer_bucket: "employer"

