host: "0.0.0.0"
port: "9000"
minio:
  config:
    internal_endpoint: "minio:9000"
    public_endpoint: "localhost:9000"
    use_ssl: false
    scheme: "http"
  buckets:
    applicant_bucket: "applicant"
    employer_bucket: "employer"
  postgres:
    host: "localhost"
    port: "5432"
    user: "postgres"
    dbname: "mydb"
    sslmode: "disable"
