name: Deploy ResuMatch Backend

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Prepare dependencies
        run: go mod tidy
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1.2
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Prepare dependencies
        run: go mod tidy
      - name: Run tests with coverage
        run: |
          go test -coverprofile=coverage.out ./...
          head -n 1 coverage.out > filtered_coverage.out
          egrep -v "(^|/)(static/|postman/|docs/|docker/|db/|configs/|grpc/auth/proto/|grpc/static/proto/|mock_[^/]*|[^/]*_easyjson\.go|[^/]*_generated\.go|vendor/)" coverage.out | tail -n +2 >> filtered_coverage.out
          go tool cover -func filtered_coverage.out | grep total

  deploy:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Deploy with SSH to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo chown -R ubuntu:ubuntu /home/ubuntu/backend/2025_1_Orange
            sudo chown -R ubuntu:ubuntu /home/ubuntu/front/2025_1_Orange
            cd /home/ubuntu/front/2025_1_Orange
            sudo docker compose down nginx || exit 1
            cd /home/ubuntu/backend/2025_1_Orange
            sudo docker compose down resumatch auth static postgres redis minio gotenberg || exit 1
            git checkout main || exit 1
            git pull origin main || exit 1
            sudo docker compose up -d --build || exit 1
            cd /home/ubuntu/front/2025_1_Orange
            sudo docker compose up -d nginx || exit 1
            cd /home/ubuntu/backend/2025_1_Orange
